// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/blogs/:blogHandle/:articleHandle": {
    params: {
      "blogHandle": string;
      "articleHandle": string;
    };
  };
  "/collections/special/v2/:handle": {
    params: {
      "handle": string;
    };
  };
  "/collections/special/:handle": {
    params: {
      "handle": string;
    };
  };
  "/sitemap/:type/:page.xml": {
    params: {
      "type": string;
      "page": string;
    };
  };
  "/blogs/:blogHandle": {
    params: {
      "blogHandle": string;
    };
  };
  "/collections/:handle": {
    params: {
      "handle": string;
    };
  };
  "/account/authorize": {
    params: {};
  };
  "/promotions": {
    params: {};
  };
  "/policies/:handle": {
    params: {
      "handle": string;
    };
  };
  "/products/:handle": {
    params: {
      "handle": string;
    };
  };
  "/account/logout": {
    params: {};
  };
  "/policies": {
    params: {};
  };
  "/promotions/:tag": {
    params: {
      "tag": string;
    };
  };
  "/account/login": {
    params: {};
  };
  "/discount/:code": {
    params: {
      "code": string;
    };
  };
  "/pages/:handle": {
    params: {
      "handle": string;
    };
  };
  "/sitemap.xml": {
    params: {};
  };
  "/blogs": {
    params: {};
  };
  "/robots.txt": {
    params: {};
  };
  "/api/request": {
    params: {};
  };
  "/account": {
    params: {};
  };
  "/account/orders": {
    params: {};
  };
  "/account/orders/:id": {
    params: {
      "id": string;
    };
  };
  "/account/addresses": {
    params: {};
  };
  "/account/profile": {
    params: {};
  };
  "/account/*": {
    params: {
      "*": string;
    };
  };
  "/search": {
    params: {};
  };
  "/cart": {
    params: {};
  };
  "/cart/:lines": {
    params: {
      "lines": string;
    };
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/blogs/:blogHandle/:articleHandle" | "/collections/special/v2/:handle" | "/collections/special/:handle" | "/sitemap/:type/:page.xml" | "/blogs/:blogHandle" | "/collections/:handle" | "/account/authorize" | "/promotions" | "/policies/:handle" | "/products/:handle" | "/account/logout" | "/policies" | "/promotions/:tag" | "/account/login" | "/discount/:code" | "/pages/:handle" | "/sitemap.xml" | "/blogs" | "/robots.txt" | "/api/request" | "/account" | "/account/orders" | "/account/orders/:id" | "/account/addresses" | "/account/profile" | "/account/*" | "/search" | "/cart" | "/cart/:lines" | "/*";
  };
  "routes/blogs.$blogHandle.$articleHandle.tsx": {
    id: "routes/blogs.$blogHandle.$articleHandle";
    page: "/blogs/:blogHandle/:articleHandle";
  };
  "routes/collections.special.v2.$handle.tsx": {
    id: "routes/collections.special.v2.$handle";
    page: "/collections/special/v2/:handle";
  };
  "routes/collections.special.$handle.tsx": {
    id: "routes/collections.special.$handle";
    page: "/collections/special/:handle";
  };
  "routes/sitemap.$type.$page[.xml].tsx": {
    id: "routes/sitemap.$type.$page[.xml]";
    page: "/sitemap/:type/:page.xml";
  };
  "routes/blogs.$blogHandle._index.tsx": {
    id: "routes/blogs.$blogHandle._index";
    page: "/blogs/:blogHandle";
  };
  "routes/collections.$handle.tsx": {
    id: "routes/collections.$handle";
    page: "/collections/:handle";
  };
  "routes/account_.authorize.tsx": {
    id: "routes/account_.authorize";
    page: "/account/authorize";
  };
  "routes/promotions._index.tsx": {
    id: "routes/promotions._index";
    page: "/promotions";
  };
  "routes/policies.$handle.tsx": {
    id: "routes/policies.$handle";
    page: "/policies/:handle";
  };
  "routes/products.$handle.tsx": {
    id: "routes/products.$handle";
    page: "/products/:handle";
  };
  "routes/account_.logout.tsx": {
    id: "routes/account_.logout";
    page: "/account/logout";
  };
  "routes/policies._index.tsx": {
    id: "routes/policies._index";
    page: "/policies";
  };
  "routes/promotions.$tag.tsx": {
    id: "routes/promotions.$tag";
    page: "/promotions/:tag";
  };
  "routes/account_.login.tsx": {
    id: "routes/account_.login";
    page: "/account/login";
  };
  "routes/discount.$code.tsx": {
    id: "routes/discount.$code";
    page: "/discount/:code";
  };
  "routes/pages.$handle.tsx": {
    id: "routes/pages.$handle";
    page: "/pages/:handle";
  };
  "routes/[sitemap.xml].tsx": {
    id: "routes/[sitemap.xml]";
    page: "/sitemap.xml";
  };
  "routes/blogs._index.tsx": {
    id: "routes/blogs._index";
    page: "/blogs";
  };
  "routes/[robots.txt].tsx": {
    id: "routes/[robots.txt]";
    page: "/robots.txt";
  };
  "routes/api.request.tsx": {
    id: "routes/api.request";
    page: "/api/request";
  };
  "routes/account.tsx": {
    id: "routes/account";
    page: "/account" | "/account/orders" | "/account/orders/:id" | "/account/addresses" | "/account/profile" | "/account/*";
  };
  "routes/account.orders._index.tsx": {
    id: "routes/account.orders._index";
    page: "/account/orders";
  };
  "routes/account.orders.$id.tsx": {
    id: "routes/account.orders.$id";
    page: "/account/orders/:id";
  };
  "routes/account.addresses.tsx": {
    id: "routes/account.addresses";
    page: "/account/addresses";
  };
  "routes/account.profile.tsx": {
    id: "routes/account.profile";
    page: "/account/profile";
  };
  "routes/account._index.tsx": {
    id: "routes/account._index";
    page: "/account";
  };
  "routes/account.$.tsx": {
    id: "routes/account.$";
    page: "/account/*";
  };
  "routes/search.tsx": {
    id: "routes/search";
    page: "/search";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/cart.tsx": {
    id: "routes/cart";
    page: "/cart" | "/cart/:lines";
  };
  "routes/cart.$lines.tsx": {
    id: "routes/cart.$lines";
    page: "/cart/:lines";
  };
  "routes/$.tsx": {
    id: "routes/$";
    page: "/*";
  };
};